### ISSUE TITLE
Is there  a delete option for the hosted web version: https://wsend.net ?

### ISSUE THREAD

**Issue by erreip** [abemassry/wsend#15]
Is there  a delete option for the hosted web version: https://wsend.net ?

**Comment by abemassry** [comment]
Yes:
https://wsend.net/134df408545e76ef27576c2e28029af9/del_screen_shot.png
![del_screen_shot](https://cloud.githubusercontent.com/assets/1616275/7037548/82d50094-dd72-11e4-9ef6-68eab636761d.png)
for each file

**Comment by erreip** [comment]
This is the screen I see. How do I now delete the uploaded file?
Thanks in advance.

![https wsend net upload](https://cloud.githubusercontent.com/assets/9080659/7522486/5e626522-f4c3-11e4-9a73-21003e2aa82f.png)

**Comment by abemassry** [comment]
For unregistered accounts there's no file list, so the file gets automatically deleted after 30 days.  It sounds like a feature request is needed where if you signup from this page the site remembers that you uploaded this file and it shows in your file list once you signup and log in.

I'll reopen to implement this.

Thanks,
Abe

**Comment by abemassry** [comment]
I've updated the backend and it should work as expected.
