### ISSUE TITLE
Cannot get ID

### ISSUE THREAD

**Issue by sergeevabc** [abemassry/wsend#23]
Dear @abemassry,
the guide says that a user must type `curl -F "start=1" https://wsend.net/createunreg` to get an id, but curl 7.86 on Windows returns nothing when I do so. What else could I try?

**Comment by abemassry** [comment]
Thank you for bringing this to my attention, I was able to reproduce it and am currently working on a fix.

**Comment by abemassry** [comment]
Looks like there must have been a change upstream, that command no longer works, but this one does:
`curl -d "start=1" https://wsend.net/createunreg`

I'm going to update the README and the cli tool and then that should close out this issue
